[package]
name = "cloudflare_resolver"
version = "1.0.0"
edition = "2021"


[dependencies]
hyper = "*"
reqwest = { version = "*", features = ["json"] }
serde = { version = "*" , features = ["derive"]}
dashmap = "5"
log = "*"

[dev-dependencies]
tokio = { version = "1.34.0", features = ["full"] }